"""Create authorization_grants table for BuyerPolicy Phase 2

Revision ID: 5e402311b352
Revises: 20260814_0075
Create Date: 2026-08-21 13:59:48.545912
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5e402311b352'
down_revision: str | None = '20260814_0075'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_grants',
    sa.Column('grant_id', sa.UUID(), nullable=False),
    sa.Column('owner_organization_id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_organization_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('access_purpose', sa.String(length=100), nullable=False),
    sa.Column('field_scope_profile', sa.String(length=100), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('record_owner_organization_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_organization_id'], ['core_identity.organizations.organization_id'], name='fk_authorization_grants_beneficiary_org'),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['core_identity.organizations.organization_id'], name='fk_authorization_grants_owner_org'),
    sa.ForeignKeyConstraint(['record_owner_organization_id'], ['core_identity.organizations.organization_id'], name='fk_authorization_grants_record_owner_org'),
    sa.PrimaryKeyConstraint('grant_id'),
    schema='core_audit',
    comment='titan.classification=PROTECTED;titan.module_owner=core_audit'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorization_grants', schema='core_audit')
    # ### end Alembic commands ###
