"""Permissoes do Core para gestao de Policies versionadas (ADR-0038/Passo 6.1)."""

from typing import Final

POLICY_CRIAR: Final = "POLICY.CRIAR"
POLICY_PUBLICAR: Final = "POLICY.PUBLICAR"
POLICY_LER: Final = "POLICY.LER"
POLICY_AVALIAR: Final = "POLICY.AVALIAR"

# ADR-0065: BuyerPolicy Fase 2 — compartilhamento contratual
POLICY_COMPARTILHAR: Final = "POLICY.COMPARTILHAR"
POLICY_COMPARTILHAMENTO_LER: Final = "POLICY.COMPARTILHAMENTO_LER"
POLICY_AVALIAR_COMPARTILHADA: Final = "POLICY.AVALIAR_COMPARTILHADA"
POLICY_COMPARTILHAMENTO_PROPOR: Final = "POLICY.COMPARTILHAMENTO_PROPOR"
POLICY_COMPARTILHAMENTO_REVISAR: Final = "POLICY.COMPARTILHAMENTO_REVISAR"

# ADR-0066 Incremento 3: composicao com a matriz de elegibilidade regulatoria.
# Exclusiva do comprador (owner do grant) -- verificado em codigo, nao em papel.
POLICY_COMPARTILHAMENTO_COMPOR: Final = "POLICY.COMPARTILHAMENTO_COMPOR"

POLICY_PERMISSIONS: Final = frozenset(
    {
        POLICY_CRIAR,
        POLICY_PUBLICAR,
        POLICY_LER,
        POLICY_AVALIAR,
        POLICY_COMPARTILHAR,
        POLICY_COMPARTILHAMENTO_LER,
        POLICY_AVALIAR_COMPARTILHADA,
        POLICY_COMPARTILHAMENTO_PROPOR,
        POLICY_COMPARTILHAMENTO_REVISAR,
        POLICY_COMPARTILHAMENTO_COMPOR,
    }
)
